### ISSUE TITLE
False postive in String#split

### ISSUE THREAD

**Issue by appleton** [mbj/mutant#1391] opened 2023-06-15 15:31 UTC
When I run mutations against code like this:

```ruby
a_string.split("/", -1)
```

I get a mutation error like this:

```diff
-  a_string.split("/", -1)
+  a_string.split("/", -2)
```

Regarding the second argument, the limit parameter, [the documentation](https://ruby-doc.org/core-3.1.0/String.html#method-i-split) for `String#split` says that:

> If negative, there is no limit to the number of fields returned, and trailing null fields are not suppressed.

This is what I want in this situation, but mutant points out that changing the number to another negative value does not produce a change in behaviour.

I have worked around it by assigning a `NEGATIVE_NUMBER = -1` constant outside of the method and passing that to the `String#split` call instead.

```ruby
NEGATIVE_NUMBER = -1
def my_method(a_string)
  a_string.split("/", NEGATIVE_NUMBER
end
```

**Comment by mbj** [comment] 2023-06-16 15:52
@appleton Mutant does not "know" its mutating `String#split` argument, as ruby is not a typed language. It knows its mutating an integer literal in the 2nd argument of a send of the selector `split` to an object. What that object is: is unknown so it could also be a `#split` method by an "random object".

So this, unless mutant where to be made runtime type aware, either via sorbet, or mutant adding dynamic reflection: Is not generically solvable in teaching mutant to avoid this specific muation.

The root cause is that `String#split` has an argument value space (negative numbers) that all behave the same, and if we where to control the `String#split` implementation: I'd say: Just change it to not behave the same on all negative nubmers but reject all negative numbers but `-1`. Or even better only allow positive numbers (excluding 0) and for the behavior of `-1` make a separate method. Avoiding this kinds of inline signalling. In languages with good sum types you'd even made a dedicated control tag etc.

So mutants finding here is "valid", it found changes you can do to the call side that have 0 impact on your semantics. But: The real fix is out of our scope as we cannot change `String#split` to not expose this troublesom semantics. Instead we have to use measures to teach mutant to NOT emit this specific mutation, this is what you can do today:

0. Fix the API we call to not have this behavior in the first place (not possible as it comes from ruby as explained above).
1. Change the AST to not produce the mutation (this is what you did!). Its slightly impefect I agree.
2. Disable the entire method for mutation testing: `# mutant:disable` comment, this is quite coarse grained.
3. Mark all `#split` calls to not be mutation tested in your project via [AST-Pattern](https://github.com/mbj/mutant/blob/main/docs/ast-pattern.md). This would affect all split calls of your entire project.
4. Not recommended: make a dedicated rspec expectation to enforce the 2nd argument is: `-1` this is the most fine grained method available for you right now, but its super annoying as you silent the observation entirely.

What mutant actually needs is the method 5) but in a per method comment doing 3). Its on my roadmap.

I hope this helps. If you can go with one of these methods let me know (and close the issue for now) I'd be happy you made an issue for method 5) if you think it would be the best solution for this issue class?

**Comment by mbj** [comment] 2023-12-02 02:05
I think this was sufficiently answered, I'm closing this for now. Feel free to continue the discussion.

**Closed by mbj** 2023-12-02 02:05 UTC
