### ISSUE TITLE
Possible bug in `foo(&block)` mutation

### ISSUE THREAD

**Issue by nepalez** [mbj/mutant#356] opened 2015-06-18 08:54 UTC
In this example:

```ruby
module Assertion

  # Builds the subclass of `Assertion::Base` with predefined `attributes`
  # and implementation of the `#check` method.
  #
  # @example
  #   IsMan = Assertion.about :age, :gender do
  #     (age >= 18) && (gender == :male)
  #   end
  #
  #   # This is the same as:
  #   class IsMan < Assertion::Base
  #     attribute :age, :gender
  #
  #     def check
  #       (age >= 18) && (gender == :male)
  #     end
  #   end
  #
  # @param [Symbol, Array<Symbol>] attributes
  #   The list of attributes for the new assertion
  # @param [Proc] block
  #   The content for the `check` method
  #
  # @return [Assertion::Base]
  #
  def self.about(*attributes, &block)
    klass = Class.new(Base)
    klass.public_send(:attribute, attributes)
    klass.__send__(:define_method, :check, &block) if block_given?

    klass
  end

end # module Assertion
```

Mutant complains that the `&block` in the `klass.__send__(:define_method, :check, &block)` is excessive.

Actually the method works even without that block (I don't know why it does), but with warnings: `warning: tried to create Proc object without a block`.

Not to mention the syntax becomes pretty weird:

```ruby
    klass.__send__(:define_method, :check) if block_given?
```

Seems like in this case the mutant complaining is a bug...gish (maybe ruby behaviour too).

**Comment by mbj** [comment] 2015-06-18 12:18
> Not to mention the syntax becomes pretty weird

It mutates to valid ruby syntax. Just the semantics defined by corelib make no sense when called like this.

Its a valid mutation. Mutant does not try to play "ruby interpreter" identifying that calling `:define_method` via `Object#__send__` does not make too much sense without a block.

If this mutation gets reported alive for you, ask yourself:

* Why do my tests not identify the absence of the block pass? The defined method `#check` does NOT have the intend semantics when the block is missing, your test should detect the absence of intent semantics of the generated `#check` method.
* Should the tests fail on warnings? (AFAIK rspec allows such a setting)

I'll close this issue as I think my answer clears the situation up. Feel free to continue discussion.

**Closed by mbj** 2015-06-18 12:18 UTC

**Comment by nepalez** [comment] 2015-06-18 12:31
My problem is the test passes as if the block would be sent there. This is not because tests are absent, I test the semantics of `#check` and in fact it HAS the intended semantics. However weird it would seem. Actually the block has been sent somehow **implicitly**. I agree this seems not a mutant problem, but the interpreter's.

And thank you! You're right about failing tests on warnings. This is really a solution

**Comment by mbj** [comment] 2015-06-18 14:39
> However weird it would seem. Actually the block has been sent somehow implicitly. I agree this seems not a mutant problem, but the interpreter's.

You are sure about that? AFAIK the block is NOT passed implicitly, if it looks like this you might be mutation testing on stale state. It might be the case the object you test against was already set-up before the test runs.

**Comment by nepalez** [comment] 2015-06-18 14:58
I do

That's how it works:
```ruby
module Test
  def self.build(&block)
    klass = Class.new(Object)
    klass.__send__(:define_method, :foo)
    klass
  end
end

Tested = Test.build { :foo }
# warning: tried to create Proc object without a block
# => Tested
Tested.new.foo
# => :foo
```

**Comment by mbj** [comment] 2015-06-18 15:05
heh, yeah, looks like an MRI bug to me. Is it reproducible under rbx/jruby?

**Comment by mbj** [comment] 2015-06-18 15:06
@nepalez BTW its quite normal mutation testing helps to find such weird edge cases.

**Comment by nepalez** [comment] 2015-06-18 15:07
Updated example above. It pushes the block anywhere

Yeah, this is why I use it. Not only for testing, but for improving code. At first for this.

**Comment by nepalez** [comment] 2015-06-18 15:08
I can try in in a quarter of hour

**Comment by nepalez** [comment] 2015-06-18 15:17
D'oh. Travis hides errors. Whatever, the answer is the "problem" occures in MRI only. Every version from 1.9.3 up to the head.
Both rbx and jruby fail as expected

**Comment by mbj** [comment] 2015-06-18 15:22
Its a MRI bug than, lets get this one reported. (You do, its your bug?). I wounder if it could hide more serious problems, where blocks get forwarded implicitly where not intend.

**Comment by nepalez** [comment] 2015-06-18 15:40
Posted it https://bugs.ruby-lang.org/issues/11283

**Comment by mbj** [comment] 2015-06-18 15:42
> The interpreter sends warning message, but doesn't raise SyntaxError as it IMHO should be.

I think that the interpreter should NOT raise a SyntaxError. Sending a message to a receiver via `Object#__send__` WITHOUT a block pass is totally valid syntax.

The bug is that MRI silently attaches an implicit block to the method send via `Object#__send__`.

**Comment by mbj** [comment] 2015-06-18 15:43
@nepalez Maybe link this thread from the bugreport so people can see context.

**Comment by nepalez** [comment] 2015-06-18 15:43
Ahh, yes. Will chanige it

**Comment by mbj** [comment] 2015-06-18 15:45
> The bug is that MRI silently attaches an implicit block to the method send via Object#__send__.

Actually the bug could be more narrow and this implicit block is only attached on calls to `define_method` via `Object#__send__`.

**Comment by nepalez** [comment] 2015-06-18 15:51
Updated

**Comment by mbj** [comment] 2015-06-19 19:07
@nepalez Congrats for getting that one fixed upstream.

**Comment by nepalez** [comment] 2015-06-19 21:32
@mbj yeah, and thank you for moving me through all of that :)
