### ISSUE TITLE
Stacktrace from mutant?

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#506] opened 2015-12-01 22:56 UTC
Have recently upgraded and am rerunning all modules with #mutant 0.8.8 (was 0.8.6).

On some modules am getting stack trace below:

```
RAILS_ENV=test bundle exec mutant -r./config/environment.rb -j6 -Iapp/mailers/aa_inviter_poster -raa_seed_inviter_poster.rb --use rspec Mailers::AaInviterPoster::AaSeedInviterPoster > log/mutant/mailers/aa_inviter_poster/aa_seed_inviter_poster_d9c082dae141ceebd75544dd962f3516_fe9d1a271e47479f946f1783187d222e_0.8.8.log
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/Users/tj/.rvm/gems/ruby-2.2.0@global/gems/memoizable-0.4.2/lib/memoizable/module_methods.rb:54:in `memoized?': undefined method `key?' for #<Set: {}> (NoMethodError)
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/method/instance.rb:16:in `new'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/methods.rb:22:in `block in call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/methods.rb:22:in `map'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/methods.rb:22:in `call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/chain.rb:14:in `block in call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/chain.rb:13:in `each'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/chain.rb:13:in `flat_map'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/chain.rb:13:in `call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/scope.rb:25:in `call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/chain.rb:14:in `block in call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/chain.rb:13:in `each'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/chain.rb:13:in `flat_map'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/chain.rb:13:in `call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/matcher/filter.rb:14:in `call'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/env/bootstrap.rb:104:in `matched_subjects'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/env/bootstrap.rb:55:in `env'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/procto-0.0.2/lib/procto.rb:62:in `public_send'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/gems/procto-0.0.2/lib/procto.rb:62:in `block in initialize'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/lib/mutant/cli.rb:20:in `run'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bundler/gems/mutant-c92dcf45603c/bin/mutant:35:in `<top (required)>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bin/mutant:23:in `load'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bin/mutant:23:in `<main>'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tj/.rvm/gems/ruby-2.2.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

This looks like it is internal to mutant. I cannot see a pattern in MY code that is causing this. 

Any guidance would be appreciated.

**Comment by mbj** [comment] 2015-12-01 23:15
@tjchambers Looks like a bug in mutant or one of its dependencies. Can you provide a reduced example that triggers this?

**Comment by mbj** [comment] 2015-12-01 23:15
Also, could you update your ruby to run `2.2.3`?

**Comment by tjchambers** [comment] 2015-12-01 23:19
I tried updating to 2.2.3 and I have loads of gems that fail. 

I will try to find the pattern that causes the failure.

**Comment by tjchambers** [comment] 2015-12-02 00:30
This appears to be a conflict of gems on my end.

I was able to solve the problem by swapping Memoist out and Adamantium::Flat in. This is a situation where I have inheritance of 2 abstract layers followed by a final subclass. The Top level abstract class was using Adamantium::Flat, and the intermediate abstract class was using Memoist (it did not need to - I am still trying to eradicate Memoist). 

When I made that one change all the mutations issues disappeared.

**Comment by tjchambers** [comment] 2015-12-02 00:31
All of the mutation issues involved this one hierarchy. There are 5 subclasses of the intermediate and all of those and the specs for the intermediate and top level were all failing. 

This is also a clear case of where I should be using composition over inheritance, but I don't want to make too many changes at once.

**Comment by tjchambers** [comment] 2015-12-02 00:32
I'd like to leave this open until I finish one pass with 0.8.8 just in case I read this wrong.

**Comment by mbj** [comment] 2015-12-02 08:46
I see. Mutant does not have any code path to deal with `Memoist`. This is not a bug, just a missing feature. Gonna close this issue for now.

**Closed by mbj** 2015-12-02 08:46 UTC
Labels: bug

**Comment by tjchambers** [comment] 2015-12-02 15:08
FYI all of my code would mutate under mutant 0.8.6 as I have been using Memoist for a while, but I have also been working recently to eliminate Memoist to reduce gem landscape. I still have 82 uses and am going to focus on eliminating those - not do to mutant. 

I prefer to use Adamantium and am looking at Memoizable where Adamantium cannot be used or am just using plain old ruby.

**Comment by tjchambers** [comment] 2015-12-10 23:59
I never was able to locate the source of the Set that was referenced by memoizable. My research let me to conclude I am using the correct thread_safe gem version which does not create a Set. 

However I was able to extricate all Memoist references and remove that gem entirely in fave of Adamantium/Memoizable.

No further action expected.

**Comment by mbj** [comment] 2015-12-11 00:28
@tjchambers thx for your final report.
