### ISSUE TITLE
Test failing within mutant

### ISSUE THREAD

**Issue by mcandre** [mbj/mutant#555] opened 2016-03-23 19:07 UTC
mutant somehow finds one of the tests to be failing in my [line-detector](https://github.com/mcandre/line-detector) gem, umodified, whereas a bare `rspec` shows no such failures.

Trace:

```
$ git clone git@github.com:mcandre/line-detector.git
$ cd line-detector/
$ bundle
$ gem install mutant-rspec

$ rspec
...

Finished in 0.00309 seconds (files took 0.21165 seconds to load)
3 examples, 0 failures

$ mutant --include lib --require line-detector --use rspec LineDetector*
--- Neutral failure ---
Original code was inserted unmutated. And the test did NOT PASS.
Your tests do not pass initially or you found a bug in mutant / unparser.
Subject AST:
s(:def, :to_s,
  s(:args),
  s(:begin,
    s(:lvasgn, :final_eol_piece,
      s(:if,
        s(:ivar, :@final_eol),
        s(:str, ", with final eol"),
        s(:str, ", without final eol"))),
    s(:dstr,
      s(:begin,
        s(:send,
          s(:ivar, :@line_ending), :to_s)),
      s(:begin,
        s(:lvar, :final_eol_piece)))))
Unparsed Source:
def to_s
  final_eol_piece = if @final_eol
    ", with final eol"
  else
    ", without final eol"
  end
  "#{@line_ending.to_s}#{final_eol_piece}"
end
Test Result:
- 3 @ runtime: 0.121157
  - rspec:0:./spec/line-detector_spec.rb:4/LineDetector#detect_line_ending_of_text correctly detects the line ending format of arbitrary text
  - rspec:1:./spec/line-detector_spec.rb:30/LineDetector#detect_line_ending_of_text correctly detects the line ending format of arbitrary text
  - rspec:2:./spec/line-detector_spec.rb:56/LineDetector#detect_final_eol_of_text detects the presence of a final end of line in arbitrary text
Test Output:
F

Failures:

  1) LineDetector#detect_line_ending_of_text correctly detects the line ending format of arbitrary text
     Failure/Error: expect(LineDetector.detect_line_ending_of_text('abc')).to eq(:none)

     NoMethodError:
       undefined method `expect' for #<RSpec::ExampleGroups::LineDetectorDetectLineEndingOfText:0x007fb18d2d9448>
     # ./spec/line-detector_spec.rb:5:in `block (2 levels) in <top (required)>'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-rspec-0.8.8/lib/mutant/integration/rspec.rb:68:in `call'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/env.rb:48:in `block in run_mutation_tests'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/isolation.rb:44:in `call'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/isolation.rb:44:in `block (3 levels) in call'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/isolation.rb:41:in `open'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/isolation.rb:41:in `block (2 levels) in call'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/isolation.rb:40:in `fork'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/isolation.rb:40:in `block in call'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/isolation.rb:37:in `pipe'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/isolation.rb:37:in `call'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/env.rb:46:in `run_mutation_tests'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/env.rb:25:in `kill'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/parallel/worker.rb:60:in `call'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/parallel/worker.rb:60:in `handle_job'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/parallel/worker.rb:45:in `handle'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/parallel/worker.rb:31:in `run'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/parallel/worker.rb:17:in `run'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/parallel/master.rb:43:in `block (2 levels) in run'
     # /Users/andrew.pennebaker/.gem/ruby/2.1.8/gems/mutant-0.8.10/lib/mutant/actor/env.rb:14:in `block in spawn'

Finished in 0.00392 seconds (files took 15.89 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/line-detector_spec.rb:4 # LineDetector#detect_line_ending_of_text correctly detects the line ending format of arbitrary text
-----------------------
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [LineDetector*]>
Integration:     Mutant::Integration::Rspec
Expect Coverage: 100.00%
Jobs:            8
Includes:        ["lib"]
Requires:        ["line-detector"]
Subjects:        9
Mutations:       496
Results:         496
Kills:           487
Alive:           9
Runtime:         16.95s
Killtime:        55.85s
Overhead:        -69.65%
Mutations/s:     29.26
Coverage:        98.19%
Expected:        100.00%
```

**Comment by mbj** [comment] 2016-03-23 21:10
Its likely your spec setup only works when the toplevel executable is `rspec`, could it be that adding a require to `rspec-expectations` in spec helper (when globally included) helps?

**Comment by backus** [comment] 2016-03-23 21:12
Running the specs locally using mutant didn't produce any neutral failures for me. Can you post your Gemfile.lock? It could also be some sort of global rspec configuration

**Comment by mbj** [comment] 2016-03-23 21:49
OT: Neutral failures are an intentional self defense build into the tool to prevent a false sense of coverage caused by integration issues just like the one you are reporting.

**Comment by backus** [comment] 2016-03-28 02:57
@mcandre any update or can we close this issue?

**Comment by mbj** [comment] 2016-03-28 18:05
@mcandre I assume its fixed, or not reproducible for now. Will close the issue, when you still have the problem please answer our questions above and I'll re-open this issue.

**Closed by mbj** 2016-03-28 18:05 UTC
Labels: question
