### ISSUE TITLE
ActiveRecord #pluck Mutation SideEffect

### ISSUE THREAD

**Issue by tjchambers** [mbj/mutant#391] opened 2015-07-30 19:17 UTC
Wanted to get on record another potentially confusing mutation result.

Alive mutation:

```
@@ -1,4 +1,4 @@
 def observations
-  Observation.where(id: effects.pluck(:observation_id))
+  Observation.where(id: effects.pluck)
 end
```

The above statement was attempting to get the observation_id column from an Effect model ActiveRecord collection to use as lookup primary keys for Observation Model. The mutation left #pluck without any column guidance (my term), and so pluck in this case fetches ALL of the columns and creates an array. The ability to pass an array of arrays to ActiveRecord is properly DEPRECATED as of current - but still "works". 

However in the particular set of effect data, the only columns that matched valid Observation Model primary key ids (not null, or 0 , or a string like 'abc') were the values in the observation_id column - the column that was consciously being plucked.

The outcome of the statement was therefore selecting the expected data, and exactly matching the spec and therefore did not kill the mutant.

For my purposes I changed the #pluck to #select which embedded the subquery into the SQL statement, and when mutated fails entirely of it's own accord killing the mutant.

**Comment by mbj** [comment] 2015-07-30 20:38
You could also fail the test in case mutant triggers a deprecation warning in AR. I think AR has a flag to turn deprecation warnings into exceptions.

**Comment by dkubb** [comment] 2015-07-30 20:42
Another option could be to do `expect(effects).to receive(:pluck).with(:observation_id).and_call_original`.

Of course this is a bit brittle compared to just asserting input/output state, it can be useful in certain circumstances where the trade-off is worth it.

**Comment by mbj** [comment] 2015-07-30 20:43
Yeah, you can nail the "non deprecated API usage". I think thats for a single instance the best choice. Later when the deprecation gets finally removed: You can change to the original spec that does only specify semantics not implementation.

As this is not a mutant bug or feature request, I'll close this issue.

**Comment by tjchambers** [comment] 2015-07-30 20:44
@mbj I like the idea of failing on deprecations anyway - that a great idea. I'll figure that out.

**Closed by mbj** 2015-07-30 20:43 UTC

**Comment by dkubb** [comment] 2015-07-30 20:46
> I like the idea of failing on deprecations anyway - that a great idea. I'll figure that out.

I kind of prefer this too; even if it only affects this one case. It removes the need to write unnecessary specs because AR's interface is (temporarily) less permissive than intended by the authors.

**Comment by tjchambers** [comment] 2015-07-30 20:47
@mbj Just to be clear I am hoping for an astute comment, and expecting you to close these, just to catalogue experiences for your "Mutant - Up and Running" or "Mutation Testing for Dummies" book due out soon I hope :)

**Comment by mbj** [comment] 2015-07-30 20:56
> @mbj I like the idea of failing on deprecations anyway - that a great idea. I'll figure that out.

IMO APIs with a "deprecation state" just increase the overall cost for everyone.

Without deprecation, you have two states "API supported", "API unsupported", with deprecation you have 2 states. "API supported", "API deprecated", "API unsupported". 

The problem is that the "deprecate before change" model:

* Forces more overall work, as you have to think about deprecations to decide if you fix now or later
* Creates more states a system can be in, especially when allowing "configurable deprecation helpers" as any bug report concerning these APIs now needs to be exermined for another global state, there is a dimension more.
* Creates more overhead for maintainers, you need to document deprecations, write code for them etc, need to track them through 2 releases instead of one.

So IMO its best to change the API (while conforming to semver), brutally without deprecation in one step, just make sure the old form raises an error (ideally compile time). For the user of a library: He *needs* to change his call sides anyway. Giving him the option to do it later for all the cost I listed above does not make sense. A user who cares about deprecation, can just fix the call sides in one step, a user who is lazy will need to do it also some day.


> @mbj Just to be clear I am hoping for an astute comment, and expecting you to close these, just to catalogue experiences for your "Mutant - Up and Running" or "Mutation Testing for Dummies" book due out soon I hope :)

I think that writing such a book would be a great experience. But the time I, as a first time author to any kind of book, would take to to this - would compared to the low expectation on finantial return - be a bad use of my time.

Mutation testing *is* awesome, but unless there is a far bigger market / usergroup it would be a wasteful decision to write a book about it.

**Comment by dkubb** [comment] 2015-07-30 21:04
I'd love to see a book too, but I think you'd have more impact right now spreading mutation testing with blog posts, and encouraging others to blog about it. If you could convince a few of the larger infleuential shops and projects to adopt it you'd probably reach more people than a niche book.

**Comment by mbj** [comment] 2015-07-30 21:06
> I'd love to see a book too, but I think you'd have more impact right now spreading mutation testing with blog posts, and encouraging others to blog about it. If you could convince a few of the larger influential shops and projects to adopt it you'd probably reach more people than a niche book.

Ack. I think a series of blog posts that exercise typical mutation scenarios / problems / integration steps is the best choice. The issues we have are a great reference to create those.

**Comment by tjchambers** [comment] 2015-07-30 21:06
While I hope you know I was joking about the book, and this is OT, there is an enormous amount of friction IMO around mutation testing, part of which are tools to make it simpler, and part is the process which even sounds a bit scary, mystical and high effort/low reward. If there weren't lots of people writing about refactoring for instance, it would not be so well-accepted (again IMHO). 

Whether you are building tools, or building a community to embrace the tools, it is a service to the development world and I appreciate it. Financial remuneration aside.

**Comment by mbj** [comment] 2015-07-30 21:08
> Financial remuneration aside.

We all have families and expenses. My free coding time is limited. So when I use it I typically want to code, not writing books ;)

**Comment by mbj** [comment] 2015-07-30 21:12
> there is an enormous amount of friction IMO around mutation testing,

Depends how far you want to change your coding. If you *listen* to all the feedback the tools give, you stop:

* Using AR
* APIs with too many states
* Rails
* Ruby 

Than the friction is gone. :P This is a partial joke.

**Comment by mbj** [comment] 2015-07-30 21:14
OH: * Quit developing and become a carpenter
