### ISSUE TITLE
Undefined method #each for nil

### ISSUE THREAD

**Issue by snusnu** [mbj/mutant#286] opened 2015-01-14 17:27 UTC
CLI to reproduce this after cloning https://github.com/snusnu/cookie

`bundle exec mutant -Ilib --require cookie --use rspec Cookie*`

Output

```
$ be mutant -Ilib --require cookie --use rspec Cookie*
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions=[<Mutant::Expression: Cookie*>] subject_ignores=[] subject_selects=[]>
Integration:     rspec
Expect Coverage: 100.00%
Jobs:            4
Includes:        ["lib"]
Requires:        ["cookie"]
(00/790)   0% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
(23/790) 100% - killtime: 0.45s runtime: 1.02s overhead: 0.57s
(43/790) 100% - killtime: 1.60s runtime: 2.02s overhead: 0.42s
(67/790) 100% - killtime: 2.52s runtime: 3.03s overhead: 0.50s
(87/790) 100% - killtime: 3.83s runtime: 4.03s overhead: 0.20s
(107/790) 100% - killtime: 4.75s runtime: 5.04s overhead: 0.28s
(127/790) 100% - killtime: 5.75s runtime: 6.04s overhead: 0.29s
(143/790)  98% - killtime: 8.26s runtime: 7.06s overhead: -1.20s
(143/790)  86% - killtime: 9.17s runtime: 8.06s overhead: -1.11s
(163/790)  85% - killtime: 9.76s runtime: 9.07s overhead: -0.69s
(186/790)  87% - killtime: 10.31s runtime: 10.08s overhead: -0.23s
(206/790)  87% - killtime: 11.37s runtime: 11.09s overhead: -0.28s
(230/790)  88% - killtime: 12.01s runtime: 12.10s overhead: 0.09s
(252/790)  89% - killtime: 13.46s runtime: 13.11s overhead: -0.36s
(271/790)  90% - killtime: 14.00s runtime: 14.11s overhead: 0.11s
(295/790)  91% - killtime: 14.82s runtime: 15.12s overhead: 0.29s
(319/790)  91% - killtime: 15.45s runtime: 16.13s overhead: 0.68s
(329/790)  88% - killtime: 16.16s runtime: 17.13s overhead: 0.98s
(329/790)  83% - killtime: 16.92s runtime: 18.14s overhead: 1.21s
(331/790)  80% - killtime: 17.69s runtime: 19.14s overhead: 1.45s
(333/790)  77% - killtime: 18.46s runtime: 20.15s overhead: 1.69s
(335/790)  74% - killtime: 19.22s runtime: 21.15s overhead: 1.94s
(337/790)  70% - killtime: 20.03s runtime: 22.16s overhead: 2.13s
(337/790)  68% - killtime: 20.54s runtime: 23.17s overhead: 2.63s
(338/790)  66% - killtime: 21.27s runtime: 24.17s overhead: 2.90s
(340/790)  63% - killtime: 22.02s runtime: 25.17s overhead: 3.15s
(367/790)  65% - killtime: 22.70s runtime: 26.18s overhead: 3.48s
(382/790)  65% - killtime: 23.21s runtime: 27.19s overhead: 3.97s
(393/790)  65% - killtime: 23.91s runtime: 28.19s overhead: 4.28s
(408/790)  65% - killtime: 24.58s runtime: 29.19s overhead: 4.62s
(409/790)  63% - killtime: 25.24s runtime: 30.20s overhead: 4.96s
(417/790)  61% - killtime: 25.87s runtime: 31.21s overhead: 5.33s
(445/790)  63% - killtime: 26.24s runtime: 32.22s overhead: 5.99s
(471/790)  64% - killtime: 27.03s runtime: 33.23s overhead: 6.20s
(498/790)  66% - killtime: 27.60s runtime: 34.24s overhead: 6.64s
(516/790)  66% - killtime: 28.28s runtime: 35.24s overhead: 6.97s
(524/790)  66% - killtime: 28.83s runtime: 36.25s overhead: 7.42s
Cookie::Header.build:/Users/snusnu/code/cookie/lib/cookie/header.rb:12
/Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:308:in `run': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:22:in `run'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:70:in `visit'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:56:in `block in visit_collection'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:55:in `each'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:55:in `visit_collection'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:288:in `run'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/reporter/cli/printer.rb:22:in `run'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/reporter/cli.rb:90:in `report'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/runner.rb:40:in `run_mutation_analysis'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/runner.rb:17:in `initialize'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/adamantium-0.2.0/lib/adamantium/class_methods.rb:17:in `new'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/procto-0.0.2/lib/procto.rb:62:in `block in initialize'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/lib/mutant/cli.rb:25:in `run'
	from /Users/snusnu/.gem/ruby/2.1.5/gems/mutant-0.7.5/bin/mutant:19:in `<top (required)>'
	from /Users/snusnu/.gem/ruby/2.1.5/bin/mutant:23:in `load'
	from /Users/snusnu/.gem/ruby/2.1.5/bin/mutant:23:in `<main>'
```

**Comment by snusnu** [comment] 2015-01-19 18:41
This seems to only happen when there are alive mutants

**Comment by mbj** [comment] 2015-01-25 17:51
@snusnu I cannot reproduce this on latest master. On `0.7.5` I can, I touched associated code in the meantime and would be happy to close this in case you can confirm it does not happen on `master` or (soon `0.7.6`).

**Comment by snusnu** [comment] 2015-01-25 21:32
@mbj yes, i can confirm that using mutant master works fine, thx!

**Closed** 2015-01-25 21:32 UTC
Labels: bug
