### ISSUE TITLE
Mutation of `super` to `super()` should not happen for a method with no arguments

### ISSUE THREAD

**Issue by mvz** [mbj/mutant#615] opened 2016-07-16 11:48 UTC
(Follow-up from #309).

It looks like mutant wants to enforce `super()` as opposed to `super`, even when those two options are completely equivalent:

```
class Foo
  def bar
    # ...
  end
end

class Bar < Foo
  def bar
    # ...
    super
  end
end
```

Here, idiomatic Ruby would favor `super` over `super()`, but mutant wants me to use `super()`, and I see no way to write a spec to favor `super`.

**Comment by dgollahon** [comment] 2017-01-29 06:06
This issue was moved to backus/mutest#22

**Comment by mbj** [comment] 2017-01-29 19:07
@mvz I believe this is a duplicate of an existing issue we agreed upon fixing. Till I've the time to reference the original I'll keep it open.

I agree on fixing it, while you cite #309 I do not agree its at all the same case. Even when this statement may spark new discussions on #309. Please do not, I do not want to lock down another discussion, hint, hint, hint.

**Comment by dgollahon** [comment] 2017-01-29 21:37
@mbj: I think this is the original issue for fixing `super()` when there are no arguments (i don't see another instance in the tracker) as it has been open for months. If it showed up in your github notifications again it is probably because I mistakenly commented on it last night (and then deleted my comment when I realized it was the wrong issue).

**Comment by mbj** [comment] 2017-01-30 00:39
> If it showed up in your github notifications again it is probably because I mistakenly commented on it last night (and then deleted my comment when I realized it was the wrong issue).

Hah, I was actually curious on why that old issue showed up. Thx for clearing that up for me.

**Comment by dgollahon** [comment] 2017-01-30 00:54
Yeah, sorry about that xD

**Closed** 2024-06-09 22:43 UTC
