### ISSUE TITLE
Document side effect of dynamic post boot insertion with alias_method shadowing

### ISSUE THREAD

**Issue by matthias-g** [mbj/mutant#765] opened 2018-11-18 22:01 UTC
In the following scenario, replacing the body of Child#one with `super` causes a SystemStackError when Child#one is being called. However mutant does not detect that this error kills the mutation that replaces the method's body with `super`. See https://github.com/matthias-g/mutant_super_bug for a running example.

```ruby
class Parent
  attr_reader :foo

  def initialize(foo)
    @foo = foo
  end

  def one
    two
  end

  def two
    false
  end
end

class Child < Parent
  def one
    foo.eql?('foo')
  end

  alias_method :two, :one
end
```

**Comment by mbj** [comment] 2018-11-23 21:35
@matthias-g So this is a valid mutation. What happens if you edit in this mutation to your code base and run the exact test subset mutant would select for this mutation? (its printed in the alive mutation report).

As you reduced the example already, can you add rspec (or minitest) so I can run it by myself?

**Comment by matthias-g** [comment] 2018-11-23 21:38
It causes a SystemStackError. You can find and run the reduced code from https://github.com/matthias-g/mutant_super_bug

**Comment by mbj** [comment] 2018-11-23 21:41
@matthias-g Where does it cause the system stack error? When running mutant, so mutant terminates abnormally?

Or inside rspec, and why is rspec not exiting nonzero so the mutation comes back red?

Can you post a printout of your interaction with mutant that shows it?

**Comment by matthias-g** [comment] 2018-11-23 21:54
If you run the mutated code (`rspec mutated.rb`), you see the following output:
```
FF

Failures:

  1) Child works for foo
     Failure/Error: two

     SystemStackError:
       stack level too deep
     # ./mutated.rb:9:in `one'
     # ./mutated.rb:19:in `one'
(....)
     # ./mutated.rb:9:in `one'
     # ./mutated.rb:19:in `one'
     # ./mutated.rb:33:in `block (2 levels) in <top (required)>'

Finished in 0.00276 seconds (files took 0.06911 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./mutated.rb:26 # Child works for foo
rspec ./mutated.rb:31 # Child works for bar
```

Mutant runs fine, but doesn't detect that the mutation should be killed:
```
$ bundle exec mutant --include . --require reproduction --use rspec Child
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [Child]>
Integration:     Mutant::Integration::Rspec
Jobs:            4
Includes:        ["."]
Requires:        ["reproduction"]
Subjects:        1
Mutations:       13
Results:         13
Kills:           12
Alive:           1
Runtime:         0.18s
Killtime:        0.29s
Overhead:        -38.54%
Mutations/s:     72.06
Coverage:        92.31%
Active subjects: 0
Child#one:.../reproduction.rb:18
- rspec:0:./reproduction.rb:26/Child works for foo
- rspec:1:./reproduction.rb:31/Child works for bar
evil:Child#one:.../reproduction.rb:18:46643
@@ -1,4 +1,4 @@
 def one
-  foo.eql?("foo")
+  super
 end
-----------------------
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [Child]>
Integration:     Mutant::Integration::Rspec
Jobs:            4
Includes:        ["."]
Requires:        ["reproduction"]
Subjects:        1
Mutations:       13
Results:         13
Kills:           12
Alive:           1
Runtime:         0.18s
Killtime:        0.29s
Overhead:        -38.54%
Mutations/s:     72.06
Coverage:        92.31%
```

**Comment by mbj** [comment] 2018-11-23 22:07
okay, I'll try by myself. Sorry to put you through this painful "get the report as I want it" process, but my time is so limited I have to force the reporters of issues (you) to do almost all the legwork.

**Comment by mbj** [comment] 2018-11-23 22:37
I'll reopen this issue, and change its title / tags a bit to remind me to put an explanation of the OSS insertion mechanism in the readme.

**Comment by mbj** [comment] 2020-11-22 23:09
@matthias-g I'm closing this as with `0.10.8` there is now a mechanism to tell mutant to consider process crashes caused by mutations as covered. 

See: https://github.com/mbj/mutant/blob/master/docs/configuration.md#coverage_criteria

**Closed by mbj** 2020-11-22 23:09 UTC
Labels: maintenance
