### ISSUE TITLE
Demo: mutant wrongly thinks it can mutate a dynamically-defined method

### ISSUE THREAD

**Issue by nathanl** [mbj/mutant#467] opened 2015-10-29 16:39 UTC
I saw some weird behavior from Mutant and created this minimal "gem" to show it: https://github.com/nathanl/mutant_test_case

The README explains how to reproduce the failure.

**Comment by nathanl** [comment] 2015-10-29 16:44
P.S. Mutant is neat! Thanks for making it. :smile:

**Comment by mbj** [comment] 2015-10-29 18:03
@nathanl Thx for this report (and the fact its executable!). And as a nitpick to your very close to flawless issue report, you *could* have had included the mutant output. Reducing the overhead even more for me.

Normally mutant should NOT select the dynamically generated methods as eligible for mutation testing. Since these have a `nil` `#source_location`. Or they are defined within a lambda.

I'm curious how you managed to bypass this checks ;)

**Comment by mbj** [comment] 2015-10-29 18:03
> P.S. Mutant is neat! Thanks for making it.

Thx. The reason is just selfish: I need it to write decent ruby code for my clients.

**Comment by nathanl** [comment] 2015-10-29 19:05
@mbj Happy to give it! See below.

In my case, the `.method(:method_name).source_location)` actually is not nil. In the example I linked, I'm calling a non-dynamic method that then calls `define_method`, and the `source_location` call points back to the contents of the non-dynamic method.

For context, the actual use case I have is here: https://github.com/nathanl/searchlight/blob/v4.1.0/lib/searchlight/search.rb#L10-L18

Basically, I have a parent class in my gem, and I use `self.define_method` to watch for method_definitions in subclasses. If the subclass defines `search_first_name`, I define a `.first_name` options accessor.

You don't have to care about those details. :) I just wanted to show that there's an actual use case beyond the minimal one I originally linked.

Output is below:

```
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [MutantTestCase::Example]>
Integration:     Mutant::Integration::Rspec
Expect Coverage: 100.00%
Jobs:            4
Includes:        ["lib"]
Requires:        ["mutant_test_case"]
(00/16) 100% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
(00/16) 100% - killtime: 0.00s runtime: 0.00s overhead: 0.00s
(07/16)  43% - killtime: 0.14s runtime: 1.01s overhead: 0.87s
MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6
- rspec:0:./spec/mutant_test_case_spec.rb:10/MutantTestCase has the method defined in the class
evil:MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6:79ff8
@@ -1,6 +1,6 @@
-def self.dynamically_add_a_method(name)
+def self.dynamically_add_a_method(name__mutant__)
   define_method(name) do
     "hello"
   end
 end
-----------------------
evil:MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6:074ed
@@ -1,6 +1,3 @@
 def self.dynamically_add_a_method(name)
-  define_method(name) do
-    "hello"
-  end
 end
-----------------------
evil:MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6:16508
@@ -1,6 +1,4 @@
 def self.dynamically_add_a_method(name)
-  define_method(name) do
-    "hello"
-  end
+  self
 end
-----------------------
evil:MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6:87191
@@ -1,6 +1,4 @@
 def self.dynamically_add_a_method(name)
-  define_method(name) do
-    "hello"
-  end
+  nil
 end
-----------------------
evil:MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6:0583b
@@ -1,6 +1,5 @@
 def self.dynamically_add_a_method(name)
   define_method(name) do
-    "hello"
   end
 end
-----------------------
evil:MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6:b32dc
@@ -1,6 +1,6 @@
 def self.dynamically_add_a_method(name)
   define_method(name) do
-    "hello"
+    raise
   end
 end
-----------------------
evil:MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6:654a0
@@ -1,6 +1,4 @@
 def self.dynamically_add_a_method(name)
-  define_method(name) do
-    "hello"
-  end
+  "hello"
 end
-----------------------
evil:MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6:3e579
@@ -1,6 +1,6 @@
 def self.dynamically_add_a_method(name)
   define_method(name) do
-    "hello"
+    nil
   end
 end
-----------------------
evil:MutantTestCase::Example.dynamically_add_a_method:/Users/nathanlong/code/mutant_test_case/lib/mutant_test_case.rb:6:4adfe
@@ -1,6 +1,6 @@
 def self.dynamically_add_a_method(name)
   define_method(name) do
-    "hello"
+    self
   end
 end
-----------------------
Mutant configuration:
Matcher:         #<Mutant::Matcher::Config match_expressions: [MutantTestCase::Example]>
Integration:     Mutant::Integration::Rspec
Expect Coverage: 100.00%
Jobs:            4
Includes:        ["lib"]
Requires:        ["mutant_test_case"]
Subjects:        1
Mutations:       16
Kills:           7
Alive:           9
Runtime:         1.01s
Killtime:        0.14s
Overhead:        629.80%
Coverage:        43.75%
Expected:        100.00%
```

**Comment by mbj** [comment] 2015-10-29 19:06
I now understand your problem. Its easy to solve, I'll PR a solution to your repo as code is better in describing the issue.

**Comment by nathanl** [comment] 2015-10-29 19:07
> Thx. The reason is just selfish: I need it to write decent ruby code for my clients.

Yes, but you don't have to answer issues from random strangers. :)

**Comment by mbj** [comment] 2015-10-29 19:08
> Yes, but you don't have to answer issues from random strangers. :)

These questions likely help to expose bugs I'd not have found otherwise. And all bugs I fix are bugs I do not have to painfully find later causing much more harm.

**Comment by mbj** [comment] 2015-10-29 19:23
@nathanl Actually it turns out its easier to explain:

Mutant does "run time mutations". AKA mutations are injected as dynamically generated monkey patches *after* (and this is important:) the library under test was loaded.

This is one of the key reasons mutant is fast. Since killing a mutation does only involve adding the monkeypatch to the already booted VM state and running rspec.

Instead when mutant would do "boot time mutations": For each mutations (and there can be thousands) mutant would have to require the library so transitively all its dependencies while injecting the mutation on the fly (this is possible, and I do it on zombification, but thats another topic).

On a bigger project the amount of time spend per mutation would to a large percentage be the amount of time to load the project and its dependencies. Upto figures like 99% overhead.

This all boils down to: The mutation *must* be observable by rspec as if the mutation was added via a monkeypatch *AFTER* the library under test was loaded.

For the vast majority of the mutation subjects this is true already. For code generating code not.

There are some tricks to make boot time mutations fast (incremental loading, state sharing upto the mutation etc) but I do not have the funding to implement these.

In your case: Creating methods at spec time should do the job. I typically recommend to create an anonymous subclass to create the methods on. So nothing persists.

To understand the effect you can also: Add the mutation you want to test as a monkeypatch to your spec helper, after the library was loaded. On manual rspec executiom you'll not see a failure and reproduced the signalling scenario.

**Comment by mbj** [comment] 2015-10-29 19:23
@nathanl This needs to be documented. But as I answered your question: I'll close it now.

**Closed by mbj** 2015-10-29 19:23 UTC
Labels: question
